/**
 * picolibrary
 *
 * Copyright 2020-2022, Andrew Countryman <apcountryman@gmail.com> and the picolibrary
 * contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/**
 * \file
 * \brief picolibrary::Testing::Automated random interface.
 */

#ifndef PICOLIBRARY_TESTING_AUTOMATED_RANDOM_H
#define PICOLIBRARY_TESTING_AUTOMATED_RANDOM_H

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <random>
#include <stdexcept>
#include <utility>

#include "picolibrary/array.h"

namespace picolibrary::Testing::Automated {

/**
 * \brief Get the automated testing pseudo-random number generator.
 *
 * \return The automated testing pseudo-random number generator.
 */
inline auto pseudo_random_number_generator() -> std::mt19937 &
{
    static auto generator = std::mt19937{ std::random_device{}() };

    return generator;
}

/**
 * \brief Generate a pseudo-random value within the specified range.
 *
 * \tparam T The type to be pseudo-randomly generated.
 *
 * \param[in] min The lower bound of the allowable range.
 * \param[in] max The upper bound of the allowable range.
 *
 * \return A pseudo-random value in the range [min,max].
 */
template<typename T>
auto random( T min, T max ) -> T
{
    return std::uniform_int_distribution<T>{ min, max }( pseudo_random_number_generator() );
}

/**
 * \brief Generate a pseudo-random value greater than or equal to a minimum value.
 *
 * \tparam T The type to be pseudo-randomly generated.
 *
 * \param[in] min The lower bound of the allowable range.
 *
 * \return A pseudo-random value in the range [min,std::numeric_limits<T>::max()].
 */
template<typename T>
auto random( T min ) -> T
{
    return random<T>( min, std::numeric_limits<T>::max() );
}

/**
 * \brief Generate a pseudo-random value.
 *
 * \tparam T The type to be pseudo-randomly generated.
 *
 * \return A pseudo-random value in the range
 *         [std::numeric_limits<T>::min(),std::numeric_limits<T>::max()].
 */
template<typename T>
auto random() -> T
{
    return random<T>( std::numeric_limits<T>::min(), std::numeric_limits<T>::max() );
}

/**
 * \brief Generate a pseudo-random bool.
 *
 * \return A pseudo-random bool.
 */
template<>
inline auto random<bool>() -> bool
{
    return random<std::uint_fast8_t>( 0, 1 );
}

/**
 * \brief Generate a pseudo-random char.
 *
 * \return A pseudo-random char in the range [' ','~'].
 */
template<>
inline auto random<char>() -> char
{
    return random<char>( ' ', '~' );
}

/**
 * \brief Generate a pair of pseudo-random values that are unique.
 *
 * \tparam T The type to be pseudo-randomly generated.
 *
 * \return A pair of pseudo-random values that are unique.
 */
template<typename T>
auto random_unique_pair() -> std::pair<T, T>
{
    auto const a = random<T>();
    auto const b = random<T>();

    return std::pair<T, T>{ a, b != a ? b : b ^ random<T>( 1 ) };
}

/**
 * \brief Generate a standard container of the specified size populated with values
 *        generated by the provided generator.
 *
 * \tparam Container The type of standard container to generate.
 * \tparam Value_Generator A nullary functor that returns the type stored in the
 *         container.
 *
 * \param[in] size The desired container size.
 * \param[in] generate_value The functor to use to generate the values stored in the
 *            container.
 *
 * \return The generated container.
 */
template<typename Container, typename Value_Generator>
auto random_container( std::size_t size, Value_Generator generate_value ) -> Container
{
    auto container = Container{};

    container.reserve( size );

    while ( size-- ) { container.push_back( generate_value() ); } // while

    return container;
}

/**
 * \brief Generate a standard container of the specified size populated with
 *        pseudo-randomly generated values.
 *
 * \tparam Container The type of standard container to generate.
 *
 * \param[in] size The desired container size.
 *
 * \return The generated container.
 */
template<typename Container>
auto random_container( std::size_t size = random<std::size_t>( 0, 15 ) ) -> Container
{
    return random_container<Container>(
        size, []() { return random<typename Container::value_type>(); } );
}

/**
 * \brief Generate an array populated with values generated by the provided generator.
 *
 * \tparam T The array element type.
 * \tparam N The number of elements in the array.
 * \tparam Value_Generator A nullary functor that returns the type stored in the array.
 *
 * \param[in] generate_value The functor to use to generate the values stored in the
 *            array.
 *
 * \return The generated array.
 */
template<typename T, std::size_t N, typename Value_Generator>
auto random_array( Value_Generator generate_value ) -> Array<T, N>
{
    Array<T, N> array;

    std::generate( array.begin(), array.end(), std::move( generate_value ) );

    return array;
}

/**
 * \brief Generate an array populated with pseudo-randomly generated values.
 *
 * \tparam T The array element type.
 * \tparam N The number of elements in the array.
 *
 * \return The generated array.
 */
template<typename T, std::size_t N>
auto random_array() -> Array<T, N>
{
    return random_array<T, N>( []() { return random<T>(); } );
}

/**
 * \brief Generate a pair of unique standard containers of the specified size populated
 *        with pseudo-randomly generated values.
 *
 * \tparam Container The type of standard container to generate.
 *
 * \param[in] size The desired container size.
 *
 * \return The pair of generated containers.
 */
template<typename Container>
auto random_unique_container_pair( std::size_t size = random<std::size_t>( 1, 15 ) )
    -> std::pair<Container, Container>
{
    if ( not( size > 0 ) ) {
        throw std::invalid_argument{
            "::picolibrary::Testing::Automated::random_unique_container_pair(): size "
            "must be greater than 0"
        };
    } // if

    auto a = random_container<Container>( size );
    auto b = random_container<Container>( size );

    if ( a == b ) {
        b[ random<std::size_t>( 0, size - 1 ) ] ^= random<typename Container::value_type>( 1 );
    } // if

    return std::pair<Container, Container>{ std::move( a ), std::move( b ) };
}

} // namespace picolibrary::Testing::Automated

#endif // PICOLIBRARY_TESTING_AUTOMATED_RANDOM_H
