/**
 * picolibrary
 *
 * Copyright 2020-2022, Andrew Countryman <apcountryman@gmail.com> and the picolibrary
 * contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/**
 * \file
 * \brief picolibrary::Testing::Unit random interface.
 */

#ifndef PICOLIBRARY_TESTING_UNIT_RANDOM_H
#define PICOLIBRARY_TESTING_UNIT_RANDOM_H

#include <cstddef>
#include <cstdint>
#include <limits>
#include <random>
#include <utility>

namespace picolibrary::Testing::Unit {

/**
 * \brief Get the unit testing pseudo-random number generator.
 *
 * \return The unit testing pseudo-random number generator.
 */
inline auto & pseudo_random_number_generator()
{
    static auto generator = std::mt19937{ std::random_device{}() };

    return generator;
}

/**
 * \brief Generate a pseudo-random value within the specified range.
 *
 * \tparam T The type to be pseudo-randomly generated.
 *
 * \param[in] min The lower bound of the allowable range.
 * \param[in] max The upper bound of the allowable range.
 *
 * \return A pseudo-random value in the range [min,max].
 */
template<typename T>
auto random( T min, T max )
{
    return std::uniform_int_distribution<T>{ min, max }( pseudo_random_number_generator() );
}

/**
 * \brief Generate a pseudo-random value greater than or equal to a minimum value.
 *
 * \tparam T The type to be pseudo-randomly generated.
 *
 * \param[in] min The lower bound of the allowable range.
 *
 * \return A pseudo-random value in the range [min,std::numeric_limits<T>::max()].
 */
template<typename T>
auto random( T min )
{
    return random<T>( min, std::numeric_limits<T>::max() );
}

/**
 * \brief Generate a pseudo-random value.
 *
 * \tparam T The type to be pseudo-randomly generated.
 *
 * \return A pseudo-random value in the range
 *         [std::numeric_limits<T>::min(),std::numeric_limits<T>::max()].
 */
template<typename T>
auto random()
{
    return random<T>( std::numeric_limits<T>::min(), std::numeric_limits<T>::max() );
}

/**
 * \brief Generate a pseudo-random bool.
 *
 * \return A pseudo-random bool.
 */
template<>
inline auto random<bool>()
{
    return static_cast<bool>( random<std::uint_fast8_t>( 0, 1 ) );
}

/**
 * \brief Generate a pseudo-random char.
 *
 * \return A pseudo-random char in the range [' ','~'].
 */
template<>
inline auto random<char>()
{
    return random<char>( ' ', '~' );
}

/**
 * \brief Generate a pair of pseudo-random values that are unique.
 *
 * \tparam T The type to be pseudo-randomly generated.
 *
 * \return A pair of pseudo-random values that are unique.
 */
template<typename T>
auto random_unique_pair()
{
    auto const a = random<T>();
    auto const b = random<T>();

    return std::pair<T, T>{ a, b != a ? b : b ^ random<T>( 1 ) };
}

/**
 * \brief Generate a standard container of the specified size populated with values
 *        generated by the provided generator.
 *
 * \tparam Container The type of standard container to generate.
 * \tparam Value_Generator A nullary functor that returns the type stored in the
 *         container.
 *
 * \param[in] size The desired container size.
 * \param[in] generate_value The functor to use to generate the values stored in the
 *            container.
 *
 * \return The generated container.
 */
template<typename Container, typename Value_Generator>
auto random_container( std::size_t size, Value_Generator generate_value )
{
    auto container = Container{};

    container.reserve( size );

    while ( size-- ) { container.push_back( generate_value() ); } // while

    return container;
}

/**
 * \brief Generate a standard container of the specified size populated with
 *        pseudo-randomly generated values.
 *
 * \tparam Container The type of standard container to generate.
 *
 * \param[in] size The desired container size.
 *
 * \return The generated container.
 */
template<typename Container>
auto random_container( std::size_t size = random<std::size_t>( 0, 15 ) )
{
    return random_container<Container>(
        size, []() { return random<typename Container::value_type>(); } );
}

} // namespace picolibrary::Testing::Unit

#endif // PICOLIBRARY_TESTING_UNIT_RANDOM_H
